Updated script to supply hostname in subject and message.

diff --git a/Code/Scripts/DoFetchAndProcessTopten b/Code/Scripts/DoFetchAndProcessTopten
--- a/Code/Scripts/DoFetchAndProcessTopten
+++ b/Code/Scripts/DoFetchAndProcessTopten
@@ -24,7 +24,7 @@ SIMPLE_SCRIPT_NAME=`basename $0`
 DOFETCH_LOG=/tmp/DoFetchLog.txt
 
 if [ ."$1" = . ]  ; then 
-	echo "$SIMPLE_SCRIPT_NAME: Missing season - ABORT!"
+	echo "$SIMPLE_SCRIPT_NAME: Missing season on `hostname` - ABORT!"
 	exit 1
 fi
 
@@ -43,6 +43,14 @@ TOPTENLOG=$GENERATED_DIR/TopTenLog-$1.txt
 # semaphore used to make sure we don't execute this script more than once at a time:
 SEMAPHORE=$GENERATED_DIR/DoFetchAndProcessTopten_Semaphore
 
+# if we're running on the PMS server we need to initialize our Perl search path (@INC)
+if hostname | grep -q "pair.com"  ; then
+	# this is for dev
+	export PERL5LIB=/usr/home/caroline/Automation/PerlCpan/Excel-Writer-XLSX-0.96/lib\
+:/usr/home/caroline/Automation/PerlCpan/Spreadsheet-Read-0.75\
+:/usr/home/caroline/Automation/PerlCpan/Spreadsheet-XLSX-0.15/lib
+fi
+#echo "PERL5LIB is '$PERL5LIB'"
 
 ##########################################################################################
 # FUNCTIONS:
@@ -60,11 +68,25 @@ SEMAPHORE=$GENERATED_DIR/DoFetchAndProcessTopten_Semaphore
 #
 ExecuteTopten() {
 	$TOPTEN $1
+	# first check to see if Topten ran at all...
+	if [ ! -f $TOPTENLOG ] ; then
+		echo "$TOPTEN failed to run (syntax error?), so we are GIVING UP"'!'
+		/usr/sbin/sendmail -f $EMAIL_NOTICE $EMAIL_NOTICE <<BUp0
+Subject: FATAL ERROR (syntax error?) during $TOPTEN $1 on `hostname`
+There was an error discovered when running $TOPTEN $1
+preventing it from running and creating a log file.
+(STARTed on $STARTDATE, ABORTed on `date`)
+BUp0
+	rm $GENERATED_DIR/DoFetchAndProcessTopten_Semaphore
+	echo "(STARTed on $STARTDATE, ABORTed (syntax error?) on `date`)"
+	exit 1;
+	fi
+	# Topten ran, but did it get an error...?
 	if grep -q "ABORT" <$TOPTENLOG ; then
 		echo "$TOPTEN got an ABORT, so we are GIVING UP"'!'
 		echo "See the TopTen log file: $TOPTENLOG"
 		/usr/sbin/sendmail -f $EMAIL_NOTICE $EMAIL_NOTICE <<BUp0
-Subject: FATAL ERROR during $TOPTEN $1
+Subject: FATAL ERROR during $TOPTEN $1 on `hostname`
 There was an error discovered when running $TOPTEN $1
 The TopTen log file is here:  $TOPTENLOG
 (STARTed on $STARTDATE, ABORTed on `date`)
@@ -107,11 +129,12 @@ LogMessage() {
 
 ##########################################################################################
 
+
 ##################  CHECK THE SEMAPHORE   ################################################
 if [ -e $SEMAPHORE ] ; then
 	# abort - program already running!
-	LogMessage "Attempted parallel executions of $SIMPLE_SCRIPT_NAME" "$(cat <<- BUp9 
-		ABORT - $SIMPLE_SCRIPT_NAME has been running since $(cat $GENERATED_DIR/DoFetchAndProcessTopten_Semaphore)
+	LogMessage "Attempted parallel executions of $SIMPLE_SCRIPT_NAME on `hostname`" "$(cat <<- BUp9 
+		ABORT - $SIMPLE_SCRIPT_NAME has been running since $(cat $GENERATED_DIR/DoFetchAndProcessTopten_Semaphore) on `hostname`
 		If you think this is wrong and $SIMPLE_SCRIPT_NAME is not running then do this:
 		   rm $GENERATED_DIR/DoFetchAndProcessTopten_Semaphore
 		(STARTed on $STARTDATE, ABORTed on $(date))
@@ -140,8 +163,8 @@ echo "$SIMPLE_SCRIPT_NAME:  Starting GetResults.pl to get the latest results for
 if grep -q "ERROR" < $GETRESULTSLOG ; then
 ########################  GOT ERROR WITH RESULT FILES  ###################################
 	tail -n -8 $GETRESULTSLOG >$TMPFILE2
-	LogMessage "FATAL ERROR during GetResults.pl $1, so we are GIVING UP!"  "$(cat <<- BUp1
-		There was an error discovered when running GetResults $1
+	LogMessage "FATAL ERROR during GetResults.pl $1 on `hostname`, so we are GIVING UP!"  "$(cat <<- BUp1
+		There was an error discovered when running GetResults $1 on `hostname`
 		Details from GetResults.pl:
 		------
 		`cat $TMPFILE2`
@@ -159,8 +182,8 @@ else
 		tail -n -13 $GETRESULTSLOG | grep -v "Get the results for USMS Records" >$TMPFILE2
 		echo "$SIMPLE_SCRIPT_NAME:  Starting $TOPTEN to process the NEW latest results for $1 (`date`)"
 		ExecuteTopten $1
-		LogMessage "A new Standings page has been generated for $1" "$(cat <<- BUp2
-			A new Standings page has been generated for the year $1 by the $0 script..
+		LogMessage "A new Standings page has been generated for $1 on `hostname`" "$(cat <<- BUp2
+			A new Standings page has been generated for the year $1 by the $0 script on `hostname`..
 			Generation was completed on `date +'%a, %b %d %G at %l:%M:%S %p %Z'`.
 			Details from GetResults.pl:
 			------
@@ -179,10 +202,10 @@ else
 		echo "$SIMPLE_SCRIPT_NAME:  Starting $TOPTEN to process the PREVIOUS latest results for $1 (`date`)"
 		ExecuteTopten $1
 		LogMessage \
-			"Found NO changes in the USMS or PAC results, but we'll generate standings anyway for $1" \
+			"Found NO changes in the USMS or PAC results, but we'll generate standings anyway for $1 on `hostname`" \
 			"$(cat <<- BUp3
 			Even though there appear to be no changes in the PAC and USMS results we 
-			generated a new standings page for the year $1 using the $0 script..
+			generated a new standings page for the year $1 using the $0 script on `hostname`..
 			Generation was completed on `date +'%a, %b %d %G at %l:%M:%S %p %Z'`.
 			Details from GetResults.pl:
 			------
@@ -197,8 +220,8 @@ else
 	else
 ########################  NO NEW RESULT FILES - DON'T GENERATE TOP 10  ###################
 		tail -n -8 $GETRESULTSLOG >$TMPFILE2
-		LogMessage "No new Standings page for $1" "$(cat <<- BUp4
-			There were no new changes for $1.
+		LogMessage "No new Standings page for $1 on `hostname`" "$(cat <<- BUp4
+			There were no new changes for $1 on `hostname`.
 			(Results were fetched and compared with previous results on `date +'%a, %b %d %G at %l:%M:%S %p %Z'`)
 			Details from GetResults.pl:
 			------
@@ -206,7 +229,6 @@ else
 			------
 			Script logs can be viewed on $ARCHIVED_TMPFILE and $ARCHIVED_TMPFILE2
 			GetResults.pl logs are at:  $GETRESULTSLOG
-			TopTen.pl logs are at: $TOPTENLOG
 			(STARTed on $STARTDATE, Terminated on `date`)
 			BUp4
 			)" "x"
